version: "3"
services:
  app:
    container_name: flask_app
    restart: always
    build: .
    links:
      - db
    command: "python3 run.py"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csv_mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: 12345
