version: "3"
services:
  app:
    restart: always
    build: .
    command: "python3 run.py"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: csv_mysql
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: 12345
